// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Explicitly load .env file
config({ path: ".env" });

const databaseUrl = process.env["POSTGRES_PRISMA_URL"];

if (!databaseUrl) {
  throw new Error("POSTGRES_PRISMA_URL is not defined in .env file");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
